config/routes.rb
Rails.application.routes.draw do
  root "dashboard#home"

  post "/search", to: 'dashboard#search', as: :search_why

  post "/follow", to: 'users#follow', as: :follow
  post "/unfollow", to: 'users#unfollow', as: :unfollow

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :profiles

  resources :ask_whies do
    collection do
      get 'my_asked_why'
    end
    member do
      get 'like'
      get 'dislike'
      get 'super_like'
      get 'reshare'
    end
  end

  resources :posts do
    collection do
      get 'user_posts'
    end
    member do
      get 'like'
    end
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_attached_file :image, 
    styles: { 
      medium: "300x300>", 
      thumb: "100x100>" 
    }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit;end

  def update
    if update_user && @profile.update(profile_params)
      redirect_to edit_profile_path, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name,:last_name,:bio, :contact, :image, :city, :interests)
    end

    def update_user
      @profile.user.update(username: params[:user][:username])
    end
end

app/views/profiles/_form.html.erb
<div class="container">
  <%= simple_form_for(@profile) do |f| %>
    <%= f.error_notification %>

    <div class='col-md-12 profile_image'>
      <img class='img-preview' style="background-image: url( <%= current_user.user_image(:medium) %> )"></img>
      <br>
      <img class='change_image' src='/assets/camera-icon.png' data-toggle="tooltip" data-placement="right" title='Click to change image'></img>
    </div>
    <br>

    <div class="form-inputs">
      <div class='row'>
        <div class='col-md-6'>
          <%= email_field_tag 'email', current_user.email, readonly: true, placeholder: 'Email' , class: "form-control" %>
        </div>

        <div class='col-md-6'>
          <%= text_field_tag 'user[username]', current_user.username, placeholder: 'Username', class: 'form-control' %>
        </div>
      </div>
      <br />
      <div class='row'>
        <div class='col-md-6'>
          <%= f.text_field :first_name, placeholder: 'First name', class: 'form-control' %>
        </div>
        <div class='col-md-6'>
          <%= f.text_field :last_name, placeholder: 'Last name', class: 'form-control' %>
        </div>
      </div>
      <br />
      <div class='row'>
        <div class='col-md-6'>
          <%= f.text_field :contact, maxlength: 10, placeholder: 'Contact number', class: 'form-control' %>
        </div>
        <div class='col-md-6'>
          <%= f.text_field :city, placeholder: 'City', class: 'form-control' %>
        </div>
      </div>
      <br />
      <div class='row'>
        <div class='col-md-12'>
          <%= f.text_area :bio, placeholder: 'Short description about yourself...', class: 'form-control' %>
        </div>
      </div>
      <br />
      <div class='row'>
        <div class='col-md-12'>
          <%= f.text_area :interests, placeholder: 'Interest', class: 'form-control' %>
        </div>
      </div>
      <br />
      <div class='row'>
        <div class='col-md-6'>
          <%= f.file_field :image, onchange: "showimagepreview(this)", accept: "image/*", class: 'hide' %>
        </div>
      </div>
    </div>
    <br />
    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  <% end %>
  <br>
  <%= link_to 'Change password', edit_user_registration_path %>
</div>

app/views/profiles/edit.html.erb
<div class='col-md-6'>
  <%= render 'form', profile: @profile %>
</div>

app/views/profiles/index.html.erb
Find me in /profiles/index

app/views/profiles/show.html.erb
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

<div class="profile-header text-center"
     style="background-image: url(../assets/img/iceland.jpg);">
  <div class="container">
    <div class="container-inner">
      <%= image_tag(@user.user_image(:thumb), class: 'img-circle media-object') %>
      <img class="img-circle media-object" src="../assets/img/avatar-dhg.png">
      <h3 class="profile-header-user"><%= @user.full_name%></h3>
      <p class="profile-header-bio">
        I wish i was a little bit taller, wish i was a baller, wish i had a girl… also.
      </p>
    </div>
  </div>

  <nav class="profile-header-nav">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#">Photos</a>
      </li>
      <li>
        <a href="#">Others</a>
      </li>
      <li>
        <a href="#">Anothers</a>
      </li>
    </ul>
  </nav>
</div>

<div class="container m-y-md" data-grid="images">
  <div>
    <img data-width="640" data-height="400" data-action="zoom" src="../assets/img/instagram_5.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_6.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_7.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_8.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_9.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_10.jpg">
  </div>

  <div>
    <img data-width="640" data-height="400" data-action="zoom" src="../assets/img/instagram_11.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_12.jpg">
  </div>

  <div>
    <img data-width="640" data-height="400" data-action="zoom" src="../assets/img/instagram_13.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_14.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_15.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_16.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_17.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_18.jpg">
  </div>

  <div>
    <img data-width="640" data-height="400" data-action="zoom" src="../assets/img/instagram_1.jpg">
  </div>

  <div>
    <img data-width="640" data-height="640" data-action="zoom" src="../assets/img/instagram_2.jpg">
  </div>
</div>