config/routes.rb
Rails.application.routes.draw do
  root "dashboard#home"

  post "/search", to: 'dashboard#search', as: :search_why

  post "/follow", to: 'users#follow', as: :follow
  post "/unfollow", to: 'users#unfollow', as: :unfollow

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :profiles

  resources :ask_whies do
    collection do
      get 'my_asked_why'
    end
    member do
      get 'like'
      get 'dislike'
      get 'super_like'
      get 'reshare'
    end
  end

  resources :posts do
    collection do
      get 'user_posts'
    end
    member do
      get 'like'
    end
  end

end

app/models/ask_why.rb
class AskWhy < ApplicationRecord

  belongs_to :user
  has_many :posts
end

app/controllers/ask_whies_controller.rb
class AskWhiesController < ApplicationController
  include AskWhiesHelper
  before_action :set_ask_why, only: [:show, :edit, :update, :destroy, :like, :dislike, :super_like, :reshare]
  
  def create
    @ask_why = current_user.ask_whies.new(ask_why_params)
    if @ask_why.save
      redirect_to root_path, notice: 'Ask why was successfully created.'
    else
      render root_path
    end
  end

  def destroy
    @ask_why.destroy
    redirect_to ask_whies_url, notice: 'Ask why was successfully destroyed.'
  end

  def dislike
    dislike_why
  end

  def edit;end

  def index
    @ask_whies = AskWhy.all
  end

  def like
    like_why
  end

  def my_asked_why
    @my_whies = current_user.ask_whies
  end

  def new
    @ask_why = AskWhy.new
  end

  def reshare
    reshare_why
  end

  def show;end

  def super_like
    super_like_why
  end

  def update
    if @ask_why.update(ask_why_params)
      redirect_to @ask_why, notice: 'Ask why was successfully updated.'
    else
      render :edit
    end
  end

  private

    def ask_why_params
      params.require(:ask_why).permit(:question)
    end

    def content_includes_why?
      ask_why_params[:question].downcase.include?('why')    
    end

    def set_ask_why
      @ask_why = AskWhy.find(params[:id])
    end
end

app/helpers/ask_whies_helper.rb
module AskWhiesHelper

  def already_following? id
    current_user.following.include?(id.to_s)
  end

  def dislike_why
	  if @ask_why.dislikes.include?(current_user.id.to_s)
      @ask_why.dislikes.delete current_user.id.to_s
    else
      @ask_why.dislikes.push current_user.id.to_s
      @ask_why.likes.delete current_user.id.to_s if @ask_why.likes.include?(current_user.id.to_s)
      @ask_why.super_likes.delete current_user.id.to_s if @ask_why.super_likes.include?(current_user.id.to_s)
    end
    @ask_why.save
  end

  def like_why
    if @ask_why.likes.include?(current_user.id.to_s)
      @ask_why.likes.delete current_user.id.to_s
    else
      @ask_why.likes.push current_user.id.to_s
      @ask_why.dislikes.delete current_user.id.to_s if @ask_why.dislikes.include?(current_user.id.to_s)
      @ask_why.super_likes.delete current_user.id.to_s if @ask_why.super_likes.include?(current_user.id.to_s)
    end
    @ask_why.save
  end

  def reshare_why
    if @ask_why.reshare.include?(current_user.id.to_s)
      @ask_why.reshare.delete current_user.id.to_s
    else
      @ask_why.reshare.push current_user.id.to_s
    end
    @ask_why.save  
  end

  def super_like_why
    if @ask_why.super_likes.include?(current_user.id.to_s)
      @ask_why.super_likes.delete current_user.id.to_s
    else
      @ask_why.super_likes.push current_user.id.to_s
      @ask_why.likes.delete current_user.id.to_s if @ask_why.likes.include?(current_user.id.to_s)
      @ask_why.dislikes.delete current_user.id.to_s if @ask_why.dislikes.include?(current_user.id.to_s)
    end
    @ask_why.save
  end


  def why_likes(why)
    why.likes.include?(current_user.id.to_s) ? 'Unike' : 'Like'
  end

  def why_dislikes(why)
    why.dislikes.include?(current_user.id.to_s) ? 'Undo-dislike' : 'Dislike'
  end

  def why_super_likes(why)
    why.super_likes.include?(current_user.id.to_s) ? 'Undo-super-like' : 'Super-like'
  end
end

app/views/ask_whies/_form.html.erb
<li class="media list-group-item p-a">
	<%= simple_form_for(@ask_why) do |f| %>
		<%= f.error_notification %>
  	<div class="input-group">
     	<%= f.text_field :question, class: 'form-control count_length', placeholder: 'Look-up for your why?', maxlength: 100 %>
      <!-- <span class='char-left'>Character left: &nbsp<b><span class='char-length'>100</span></b></span>
  		<span class='error-msg text-left'></span> -->
    	<div class="input-group-btn">
      	<button type="button" class="btn btn-default">
        	<span class="icon icon-camera"></span>
      	</button> 	
      	<%= f.button :submit, class: 'btn btn-primary' %>
    	</div>
    <% end %>
  </div>
  <div id="why_error_message">
    <span></span>
  </div>
</li>

app/views/ask_whies/dislike.js.erb
$('.why_card_<%= @ask_why.id %>').html("<%= escape_javascript render partial: 'common/why_card_options', locals: { why: @ask_why } %>")

app/views/ask_whies/edit.html.erb
<h3>Editing Ask Why</h3>

<%= render 'form', ask_why: @ask_why %>

<%= link_to 'Show', @ask_why %> |
<%= link_to 'Back', ask_whies_path %>

app/views/ask_whies/index.html.erb
<% @ask_whies.each do |why| %>
  <li class="media list-group-item p-a">
  <div class="left-section">
    <div class="media-left">
      <%= link_to profile_path(why.user) do %>
        <%= image_tag(why.user.user_profile_image,class: "img-circle",style: "width: 100%;")%>
      <%end%>
    </div>
       <div class="why_card_options">
        <% unless created_by_user?(why.user) %>
        <%= render partial: 'common/why_card_options', locals: { why: why } %>&nbsp;
          <% unless params[:controller] == "ask_whies" && params[:action] == "show" %>
          <ul>
          <li>
            <%= link_to 'Reply', "#-" %>
            <span><%= why.posts.count %></span></li>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="media-body">
      <div class="media-heading">
        <small class="pull-right text-muted">
          <%= time_ago_in_words(why.created_at) %>
          <%= link_to "delete",ask_why_path(why), method: :delete if created_by_user? why.user %>
          <%= link_to "edit",edit_ask_why_path(why) if created_by_user? why.user %>
        </small>
        <h5><%= why.user.full_name %></h5>
      </div>
      <p><%= why.question %></p>
      <div class="media-body-inline-grid" data-grid="images">
        <div style="display: none">
          <img data-action="zoom" data-width="1050" data-height="700" src="/assets/unsplash_1.jpg">
        </div>

        <div style="display: none">
          <img data-action="zoom" data-width="640" data-height="640" src="/assets/instagram_1.jpg">
        </div>

        <div style="display: none">
          <img data-action="zoom" data-width="640" data-height="640" src="/assets/instagram_13.jpg">
        </div>

        <div style="display: none">
          <img data-action="zoom" data-width="1048" data-height="700" src="/assets/unsplash_2.jpg">
        </div>
      </div>
      <ul class="media-list m-b">
        <%= render partial: 'posts/form' ,locals: {why: why} %>
        <%= render template: "posts/index" , locals: {why: why} %>
      </ul>
    </div>
  </li>
<% end %>

app/views/ask_whies/like.js.erb
$('.why_card_<%= @ask_why.id %>').html("<%= escape_javascript render partial: 'common/why_card_options', locals: { why: @ask_why } %>")

app/views/ask_whies/my_asked_why.html.erb
<h3><%= link_to 'Ask Why', new_ask_why_path %></h3>

<div class='col-md-12'>
  <% @my_whies.each do |why| %>
    <div class='col-md-3 why-card'>

      <div class='asked-by'>
        <%= image_tag(why.user.user_image(:original)) %><br>
        <span><b><%= why.user.full_name %></b></span>
      </div>

      <div class='content'>
        <%= why.question %>
        <span><%= image_tag('/assets/why.png') %></span>
      </div>

      <div class='options'>
        <%= link_to 'Edit', edit_ask_why_path(why) %>&nbsp
        <%= link_to 'Destroy', ask_why_path(why), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/ask_whies/new.html.erb
<h3>New Ask Why</h3>
<div class='col-md-6'>
  <%= render 'form', ask_why: @ask_why %>
</div>

app/views/ask_whies/reshare.js.erb
$('.why_card_<%= @ask_why.id %>').html("<%= escape_javascript render partial: 'common/why_card_options', locals: { why: @ask_why } %>")

app/views/ask_whies/show.html.erb
<div class='col-md-12'>
  <div class='col-md-4'>
    <div class='why-card'>

      <div class='asked-by'>
        <%= image_tag(@ask_why.user.user_image(:original)) %><br>
        <span><b><%= @ask_why.user.full_name %></b></span>
      </div>

      <div class='content'>
        <%= @ask_why.question %>
        <span><%= image_tag('/assets/why.png') %></span>
      </div>

      <% unless created_by_user?(@ask_why.user) %>
        <%= render partial: 'common/why_card_options', locals: { why: @ask_why } %>
        <% unless params[:controller] == "ask_whies" && params[:action] == "show" %>
          <%= link_to 'Reply', ask_why_path(why) %>
        <% end %>
      <% end %>
    </div>

    <% @ask_why.posts.each do |post| %>
      <div class='why-card-posts'>

        <div class='user'>
          <%= image_tag(post.user.user_image(:thumb)) %>
          <span><b><%= post.user.full_name %></b></span>
        </div>

        <div class='content'>
          <%= post.content %>
        </div>

        <div class='image'>
          <%= image_tag(post.image.url(:medium)) if post.image.present? %>
        </div>

        <div class='options post_card_<%= post.id %>'>
          <%= render 'common/post_card_options', post: post %>
        </div>
      </div>
    <% end %>

    <% unless created_by_user?(@ask_why.user) %>
      <%= render 'posts/form', post: @ask_why.posts.new %>
    <% end %>
  </div>
</div>

app/views/ask_whies/super_like.js.erb
$('.why_card_<%= @ask_why.id %>').html("<%= escape_javascript render partial: 'common/why_card_options', locals: { why: @ask_why } %>")