config/routes.rb
Rails.application.routes.draw do
  root "dashboard#home"

  post "/search", to: 'dashboard#search', as: :search_why

  post "/follow", to: 'users#follow', as: :follow
  post "/unfollow", to: 'users#unfollow', as: :unfollow

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :profiles

  resources :ask_whies do
    collection do
      get 'my_asked_why'
    end
    member do
      get 'like'
      get 'dislike'
      get 'super_like'
      get 'reshare'
    end
  end

  resources :posts do
    collection do
      get 'user_posts'
    end
    member do
      get 'like'
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :ask_why

  has_attached_file :image, 
    styles: { 
      medium: "300x300>", 
      thumb: "100x100>" 
    }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper

  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      redirect_to root_path
    end
  end

  def edit;end

  def destroy
    @post.destroy
    redirect_to user_posts_posts_path, notice: 'Post was successfully destroyed.'
  end

  def index
    @posts = Post.all
  end

  def like
    like_post
  end

  def new
    @post = Post.new
  end

  def show;end

  def update
    if @post.update(post_params)
      redirect_to @post.ask_why, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def user_posts
    @posts = current_user.posts
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content,:image,:video,:ask_why_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def like_post
    if @post.likes.include?(current_user.id.to_s)
      @post.likes.delete current_user.id.to_s
    else
      @post.likes.push current_user.id.to_s
    end
    @post.save
  end
end

app/views/posts/_form.html.erb
<!-- <li class="media list-group-item p-a"> -->
  <%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>
    <%= f.hidden_field :ask_why_id, value: why.id  unless @post.id.present? %>
    <div class="input-group">
      <%= f.text_field :content, class: 'form-control count_length', rows: 3, placeholder: 'Share your reason for why?....', maxlength: 100 %>
      <div class="input-group-btn">
       <div class="btn btn-default image-preview-input">
        <span class="icon icon-camera"></span>
          <span class="image-preview-input-title"></span>
          <%= f.file_field :image, accept: "image/*" %><!-- rename it -->
        </div>
          <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<!-- </li> -->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% why.posts.each do |post| %>
  <li class="media">
  <a class="media-left" href="<%= profile_path(post.user)%>">
    <%= image_tag(post.user.user_image(:thumb),class: "media-object img-circle") %>
  </a>
  <div class="media-body">
    <strong><%= post.user.full_name %></strong>
    <small class="pull-right text-muted">
      <%=link_to "delete",post_path(post), method: :delete if (created_by_user? post.user or created_by_user? why.user) %>
      <%=link_to "edit",edit_post_path(post), data: { why: why} if created_by_user? post.user %>
    <%= time_ago_in_words(post.created_at) %></small>
    <%= post.content %>
    <div class='image'>
      <%= image_tag(post.image.url(:medium),class: "image", data: {action: 'zoom'}) if post.image.present? %>
    </div>
  </div>
  </li>
<% end %>

app/views/posts/like.js.erb
$('.post_card_<%= @post.id %>').html("<%= escape_javascript render partial: 'common/post_card_options', locals: { post: @post } %>")

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class='col-md-6'>
  <%= render 'form', post: @post %>
</div>

app/views/posts/user_posts.html.erb
<h1>Posts</h1>

<div class='col-md-12'>
  <% @posts.each do |post| %>
    <div class='col-md-3 why-card'>

      <div class='content'>
        <%= post.content %>
      </div>

      <div class='image'>
        <%= image_tag(post.image.url(:medium)) if post.image.present? %>
      </div>

      <div class='options'>
        <%= link_to 'Edit', edit_post_path(post) %>&nbsp
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>