config/routes.rb
Rails.application.routes.draw do
  root "dashboard#home"

  post "/search", to: 'dashboard#search', as: :search_why

  post "/follow", to: 'users#follow', as: :follow
  post "/unfollow", to: 'users#unfollow', as: :unfollow

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :profiles

  resources :ask_whies do
    collection do
      get 'my_asked_why'
    end
    member do
      get 'like'
      get 'dislike'
      get 'super_like'
      get 'reshare'
    end
  end

  resources :posts do
    collection do
      get 'user_posts'
    end
    member do
      get 'like'
    end
  end

end

app/views/common/_follow_unfollow_link.html.erb
<div class='options opt_<%= user.id %>'>
  <% if already_following?(user.id) %>
  	<a class="btn btn-primary-outline btn-sm" data-remote="true" rel="nofollow" data-method="post" href="<%= unfollow_path(user_id: user.id) %>"><span class="icon icon-add-user">&nbsp; Unfollow (<%= user.followers.count %>)</span></a>
  <% else %>
  	<a class="btn btn-primary-outline btn-sm" data-remote="true" rel="nofollow" data-method="post" href="<%= follow_path(user_id: user.id) %>"><span class="icon icon-add-user">  &nbsp; Follow (<%= user.followers.count %>)</span></a>
  <% end %>

</div>

app/views/common/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top app-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-main">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">
        <img src="/assets/brand-white.png" alt="brand">
      </a>
    </div>
    <div class="navbar-collapse collapse" id="navbar-collapse-main">

        <ul class="nav navbar-nav hidden-xs">
          <li>
            <a href="<%=root_path%>">Home</a>
          </li>
          <li class="active">
            <a href="<%=profile_path(current_user)%>">Profile</a>
          </li>
          <li>
            <a data-toggle="modal" href="#msgModal">Messages</a>
          </li>
          <li>
            <a href="#-">Docs</a>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right m-r-0 hidden-xs">
          <li >
            <a class="app-notifications" href="#-">
              <span class="icon icon-bell"></span>
            </a>
          </li>
          <li>
            <button class="btn btn-default navbar-btn navbar-btn-avitar" data-toggle="popover">
              <%= image_tag(current_user.user_profile_image, class: "img-circle") if current_user%>
            </button>
          </li>
        </ul>

        <form class="navbar-form navbar-right app-search" role="search">
          <div class="form-group">
            <%= form_tag '#-', method: :post do |f| %>
              <%= text_field_tag :search, '', placeholder: 'Search user with name or any why?' , class: 'search_field form-control', data: {action: "grow"} %>
            <% end %>
          </div>
        </form>

        <ul class="nav navbar-nav hidden-sm hidden-md hidden-lg">
          <li><a href="<%=root_path%>">Home</a></li>
          <li><a href="<%=profile_path(current_user)%>">Profile</a></li>
          <li><a href="#-">Notifications</a></li>
          <li><a data-toggle="modal" href="#msgModal">Messages</a></li>
          <li><a href="#-">Docs</a></li>
          <li><a href="<%= edit_profile_path(current_user.profile) %>" data-action="growl">Account</a></li>
          <li><a href="<%= users_sign_out_path %>">Logout</a></li>
        </ul>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav hidden">
            <li><a href="<%= edit_profile_path(current_user.profile) %>">Account</a></li>
            <li><a href="<%= users_sign_out_path %>">Logout</a></li>
          </ul>
        <% end %>
      </div>
  </div>
</nav>

app/views/common/_post_card_options.html.erb
<% if created_by_user?(post.user) %>
  <%= link_to 'Edit', edit_post_path(post) %>&nbsp
  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
  <%= link_to (post.likes.include?(current_user.id.to_s) ? 'Unike' : 'Like'), like_post_path(post), remote: true %>&nbsp
  (<%= post.likes.length %>)
  <%#= link_to 'Un-like', '#-' %>&nbsp
<% end %>

app/views/common/_why_card_options.html.erb
<div class='options why_card_<%= why.id %>'>
<ul>
  <li><%= link_to image_tag('/assets/icon-one.png') + (why_likes(why)), like_ask_why_path(why), remote: true %><br>
  <span><%= why.likes.count %></span></li>

 <li><%= link_to image_tag('/assets/icon-two.png') + (why_dislikes(why)), dislike_ask_why_path(why), remote: true %><br>
  <span><%= why.dislikes.count %></span></li>

  <li><%= link_to image_tag('/assets/icon-three.png')+(why_super_likes(why)), super_like_ask_why_path(why), remote: true %><br>
  <span><%= why.super_likes.count %></span></li>

  <li><%= link_to image_tag('/assets/icon-four.png') + (why.reshare.include?(current_user.id.to_s) ? 'Shared' : 'Reshare'), reshare_ask_why_path(why), remote: true %></li>
</div>